// const sampleListings = [
//   {
//     title: "Lakeside A-Frame Cabin",
//     description:
//       "Relax in this beautiful A-frame cabin nestled beside a tranquil lake. Ideal for peaceful weekends away.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1600047509358-018e7ab0f00c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 950,
//     location: "Lake Placid",
//     country: "United States",
//   },
//   {
//     title: "Modern Apartment in Paris",
//     description:
//       "Stay in the heart of Paris with Eiffel Tower views and a cozy, modern interior.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1549921296-3a4b43b3e8de?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2200,
//     location: "Paris",
//     country: "France",
//   },
//   {
//     title: "Coastal Cottage in Cornwall",
//     description:
//       "Charming cottage near the beach with stunning sea views. Perfect for a family vacation.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1600267185112-2d5d4b4a5b6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1300,
//     location: "Cornwall",
//     country: "United Kingdom",
//   },
//   {
//     title: "Skyline View Apartment",
//     description:
//       "Enjoy the city skyline from your balcony in this sleek high-rise apartment.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1700,
//     location: "Chicago",
//     country: "United States",
//   },
//   {
//     title: "Countryside Farmhouse Retreat",
//     description:
//       "Unplug and enjoy country living in this peaceful farmhouse surrounded by rolling hills.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1504593811423-6dd665756598?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1000,
//     location: "Nashville",
//     country: "United States",
//   },
//   {
//     title: "Luxury Villa with Infinity Pool",
//     description:
//       "Indulge in luxury at this hillside villa featuring a private infinity pool and ocean views.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1613060505894-2f2ecfd5d539?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 4800,
//     location: "Santorini",
//     country: "Greece",
//   },
// ];

// module.exports = { data: sampleListings };

const sampleListings = [
  {
    title: "Mountain View Cabin",
    description: "Relax in this cozy cabin with breathtaking views of the mountains. Perfect for nature lovers and hikers.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Seaside Villa",
    description: "Luxurious seaside villa with private beach access and stunning ocean views.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Countryside Retreat",
    description: "Escape to the serene countryside in this charming retreat surrounded by nature.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
  },
  {
    title: "Urban Loft",
    description: "Modern loft in the heart of the city. Close to cafes, shopping, and nightlife.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Lakefront Cottage",
    description: "Charming cottage on the lake. Enjoy fishing, kayaking, and peaceful evenings by the water.",
    image: "https://images.unsplash.com/photo-1600585154783-0c8e5f4e7c61?auto=format&fit=crop&w=800&q=60",
    price: 1600,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Tropical Paradise",
    description: "Beachfront bungalow with a hammock and crystal-clear water steps away.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Maui",
    country: "United States",
  },
  {
    title: "Historic Castle",
    description: "Live like royalty in this restored 15th-century castle with modern comforts.",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=60",
    price: 5500,
    location: "Loire Valley",
    country: "France",
  },
  {
    title: "Desert Dome Home",
    description: "Unique dome home in the desert with stunning night skies and peace.",
    image: "https://images.unsplash.com/photo-1604079623172-6a7fa4e1cbee?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Rainforest Treehouse",
    description: "Sleep among the treetops in this eco-friendly treehouse deep in the rainforest.",
    image: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=800&q=60",
    price: 2400,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Ski Chalet",
    description: "Ski-in, ski-out access with cozy fireplaces and snow-covered views.",
    image: "https://images.unsplash.com/photo-1589987601745-8b6b221bc7e9?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "City Apartment",
    description: "Contemporary apartment with skyline views, perfect for business or pleasure.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Rustic Farmhouse",
    description: "Classic farmhouse with rustic charm, open fields, and a barn.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    price: 1100,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Cliffside Haven",
    description: "Dramatic cliffside retreat with sweeping views of the ocean and sunsets.",
    image: "https://images.unsplash.com/photo-1600585154534-0ef09a4db9c9?auto=format&fit=crop&w=800&q=60",
    price: 4100,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Snowy Lodge",
    description: "Cozy winter lodge with a fireplace and access to snow sports.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Banff",
    country: "Canada",
  },
  {
    title: "Island Hideaway",
    description: "Private island experience with luxury amenities and total seclusion.",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=60",
    price: 7000,
    location: "Fiji",
    country: "Fiji",
  },
  {
    title: "Modern City Apartment",
    description: "Stay in the heart of the city in this modern and stylish apartment. Close to all major attractions and nightlife.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "New York",
    country: "United States",
  },
  {
    title: "Rustic Countryside Farmhouse",
    description: "Experience peace and quiet in this rustic farmhouse surrounded by open fields and fresh air.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=60",
    price: 1300,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Tropical Island Bungalow",
    description: "Enjoy the sun and sea in this beautiful beachfront bungalow, just steps from the turquoise water.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Bora Bora",
    country: "French Polynesia",
  },
  {
    title: "Historic European Loft",
    description: "Charming loft located in a historic building with exposed brick and wooden beams.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 1600,
    location: "Prague",
    country: "Czech Republic",
  },
  {
    title: "Lakefront Cottage",
    description: "Unwind at this serene lakefront cottage with a private dock and canoe access.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 1400,
    location: "Ontario",
    country: "Canada",
  },
  {
    title: "Desert Dome Retreat",
    description: "Stay under the stars in this unique dome retreat in the peaceful desert landscape.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    price: 1100,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Luxury Ski Chalet",
    description: "Perfect for a winter escape, this luxury chalet includes a fireplace, hot tub, and mountain access.",
    image: "https://images.unsplash.com/photo-1600585153470-8a51500f7f30?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Jungle Treehouse",
    description: "Immerse yourself in nature with this treehouse experience in the heart of the jungle.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
    price: 1250,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Secluded Cliffside Villa",
    description: "Watch stunning sunsets from your own private cliffside villa overlooking the ocean.",
    image: "https://images.unsplash.com/photo-1600596542788-48d4b5b0ec1e?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Scandinavian Glass Cabin",
    description: "Sleep under the northern lights in this all-glass cabin in the remote wilderness.",
    image: "https://images.unsplash.com/photo-1570732285972-0d76813aa181?auto=format&fit=crop&w=800&q=60",
    price: 2100,
    location: "Lapland",
    country: "Finland",
  },
  {
    title: "Mediterranean Rooftop Flat",
    description: "Enjoy warm evenings on the rooftop terrace of this cozy flat in the Mediterranean old town.",
    image: "https://images.unsplash.com/photo-1618773928121-9c3dbb7b0b53?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Barcelona",
    country: "Spain",
  },
  {
    title: "Rainforest Eco Lodge",
    description: "Sustainable living meets comfort in this eco-lodge nestled deep in the rainforest.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=60",
    price: 1450,
    location: "Amazon",
    country: "Brazil",
  },
  {
    title: "Charming Canal House",
    description: "Stay in a beautiful canal-side house in the heart of this picturesque European city.",
    image: "https://images.unsplash.com/photo-1578932667683-e89e4c0cde53?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Amsterdam",
    country: "Netherlands",
  }
];


  module.exports = { data: sampleListings };
